services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    restart: always
    tty: true
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 9876:5432